<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::table('settlements', function (Blueprint $table) {
            // engine = generated by SettlementService, manual = user-created (e.g. stock buy-backs)
            $table->string('source', 16)->default('engine')->after('amount');
            // categorize rows in UI
            $table->string('type', 32)->default('expense')->after('source');
            $table->string('title')->nullable()->after('type');
            $table->text('note')->nullable()->after('title');
        });
    }

    public function down(): void
    {
        Schema::table('settlements', function (Blueprint $table) {
            $table->dropColumn(['source', 'type', 'title', 'note']);
        });
    }
};

